/**********************************************************************************
 * @filename      : CLM_SocPlaAllocationManage_Ctrl_ts.cls
 * @project-name  : LK보험중계_신규계약관리시스템 구축
 * @author        : i2max
 * @date          : 2026-01-26 (월)
 * @group         :
 * @group-content :
 * @description   : 
 * @target-class  : 
 * @reference     : 
 * @copyright     : LK Insurance Services
 * @modification  Log
 * ===================================================================
 * ver   date             author            description
 * ===================================================================
 * 1.0   2026-01-26      i2max     Create
**********************************************************************************/
@IsTest
private class CLM_SocPlaAllocationManage_Ctrl_ts {

    @IsTest
    static void testBehavior() {
    }


}